[global]
   workgroup = WORKGROUP
   server string = Arch Samba Server
   security = user
   map to guest = Bad User
   smb ports = 445
   server min protocol = SMB2
   disable netbios = yes

   aio read size = 1
   aio write size = 1
   use sendfile = yes

[media]
   path = /mnt/smb
   browseable = yes
   writable = yes
   guest ok = yes
   public = yes
