#! /usr/bin/bash

set -uexo pipefail

up() {
    sudo mkdir -p /data/gitlab/data
    sudo mkdir -p /data/gitlab/etc
    sudo mkdir -p /data/gitlab/log
    sudo mkdir -p /data/gitlab-runner/etc
    docker-compose up -d
}

down() {
    docker-compose down
    # sudo rm -rf /data/gitlab/data
    # sudo rm -rf /data/gitlab/etc
    # sudo rm -rf /data/gitlab/log
    # sudo rm -rf /data/gitlab-runner/etc
}

case $1 in
    up) up;;
    down) down;;
esac
