k9s:
  refreshRate: 2
  maxConnRetry: 5
  enableMouse: true
  headless: true
  logoless: false
  crumbsless: false
  readOnly: false
  noExitOnCtrlC: false
  noIcons: false
  logger:
    tail: 100
    buffer: 5000
    sinceSeconds: 300
    fullScreenLogs: false
    textWrap: true
    showTime: true
  currentContext: minikube
  currentCluster: minikube
  clusters:
    externalCluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - current-prod
        - kube-system
        - default
      view:
        active: deploy
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    internalCluster:
      namespace:
        active: all
        lockFavorites: false
        favorites:
        - default
      view:
        active: ctx
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.31
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
    minikube:
      namespace:
        active: default
        lockFavorites: false
        favorites:
        - default
      view:
        active: service
      featureGates:
        nodeShell: false
      shellPod:
        image: busybox:1.35.0
        command: []
        args: []
        namespace: default
        limits:
          cpu: 100m
          memory: 100Mi
      portForwardAddress: localhost
  thresholds:
    cpu:
      critical: 90
      warn: 70
    memory:
      critical: 90
      warn: 70
  screenDumpDir: /tmp/k9s-screens-alan
